name: Publish Website

on:
  push:

jobs:

  deploy:
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
    
      - run: mkdir -p dist
      - run: echo "<h1>${{ github.sha }}</h1>" > dist/index.html
      
      - uses: amKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          local-dir: ./dist/
          dangerous-clean-slate: true
          security: strict
